#pragma once
#ifndef __GAME_OBJECT_TYPE__
#define __GAME_OBJECT_TYPE__
enum GameObjectType {
	NONE = -1,
	SHIP,
	TARGET,
	PLAYER,
	PLANE,
	BACKGROUND,
	START_BUTTON,
	SCENE1_BUTTON,
	SCENE2_BUTTON,
	RESTART_BUTTON,
	BACK_BUTTON,
	NEXT_BUTTON,
	BRICK,
	BALL,
	POOL,
	NUM_OF_TYPES,
	ENEMY
};
#endif /* defined (__GAME_OBJECT_TYPE__) */